public class MathOperations 
{
	public static void Addition(integer x, integer y)
    {
        system.debug('Addition Result is ----- '+ (x+y));
    }
    public void Multiplication(integer x, integer y, integer z)
    {
        system.debug('Multiplication Result is ----- '+ (x*y*z));
    }
    public void Substraction(integer x, integer y)
    {
        system.debug('Substraction Result is ----- '+ (x-y));
    }
}