public class NumberOfOccuranceInaString 
{
    public static void sss(){
        string name= 'aaakaash';
        integer lenght = name.length();
        system.debug(lenght);
        string test='aaakkaasshhaa';
system.debug('***A'+test.countMatches('a'));
        system.debug('***K'+test.countMatches('k'));
        system.debug('***s'+test.countMatches('s'));
		system.debug('***h'+test.countMatches('H'));
        
        List<string> ls = new list<string>();
        ls.add('one');
        ls.add('one');
        ls.add('one');
        ls.add('one');
        ls.add('two');
        ls.add('two');
        if(!ls.isEmpty())
        {

        }

    }
}